import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import LibSqlite from '@/lib/LibSqlite';
import { useEffect, useState } from 'react';
//type
type IPostItem = {
  id: number,
  title : string,
  content : string,
}

//
export default function Home() {
  const [postId, setPostId] = useState(0);
//  const [postItem, setPostItem] = useState<IPostItem>({id:0, title:"", content:""});
  const [postItem, setPostItem] = useState([]);

  /**
  * getList
  * @param
  *
  * @return
  */
  const getList = async function() {
    try {   
      const db = await LibSqlite.getDb();
      const sql = `
      SELECT id, title, content FROM Post ORDER BY id DESC;
      `;
      console.log(sql);
      const result = await LibSqlite.select(db, sql);
      if(result === null) {
        return;
      }
      const items: any[] = [];
      result.forEach(function (item: any){
        let row = {id: 0, title: "", content: ""};
        if(item.length > 0) {
          row.id = item[0];
          row.title = item[1];
          row.content = item[2];
        }
        items.push(row);
      });
      //@ts-ignore
      setPostItem(items);
//      console.log(items);
    } catch (e) {
      console.error(e);
      alert("error, getList");
    }
  }
  /**
  * Start proc
  * @param
  *
  */
  useEffect(() => {
    (async() => {
      getList();
    })()    
  }, []);
  //
//console.log(postItem);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/test">Test
      </Link>       
      <hr />
      <h1>Hello, Next.js + SQLite3 WASM</h1>
      <hr />
      {postItem.map((item: IPostItem, index) => {
//console.log(item );
      return (
        <div key={index}><h3>{item.title}</h3>
          ID: {item.id}
          <hr />
        </div>
      )   
      })}
    </div>
  )
}

/*
{`/post_show?id=${props.id}`}
  <Link href={`/posts?id=${item.id}`}><h3>{item.title}</h3>
  </Link>
*/